Cookie secret file
NLnetLabs/unbound pull request #1090
Opened 2024-06-14 08:20 UTC by wcawijngaards

This creates a new option to store the cookies in a file and manage them with remote control.

The `cookie-secret-file: "unbound_cookiesecrets.txt"` option can be used with the unbound-control `add_cookie_secret`, `drop_cookie_secret`, `activate_cookie_secret` and `print_cookie_secrets` commands. Code has been used from the NSD implementation of it.

This fixes #1088 .

2024-08-01 19:53 UTC, gthess requested changes
Looks good!
Just a question about writing to file.
Some changes for the test and some documentation edits will follow in a PR; that's why the "request changes" status.

2024-08-01 19:53 UTC, gthess commented on daemon/remote.c
> +	if(worker->thread_num == 0 && !cookie_secret_file_dump(ssl, worker)) {
Do we need to write two times to file? Once for the current state and one after the addition? Why not just after the addition?
Also similar question for `do_drop_cookie_secret()`, `do_activate_cookie_secret()`.

2024-08-01 20:07 UTC, gthess commented
If the attached PR (https://github.com/NLnetLabs/unbound/pull/1116) is merged here, then a squash and merge of this back to master should do it.

2024-08-02 09:05 UTC, wcawijngaards commented on daemon/remote.c
> +	if(worker->thread_num == 0 && !cookie_secret_file_dump(ssl, worker)) {
NSD does this as well, https://github.com/NLnetLabs/nsd/blob/b88421be3b5654eed5e2c432d20172b72ea12052/remote.c#L2410 . This checks that the file is actually writable before making the change. It seems a useful safeguard, so I do not think it is an issue.

2024-08-02 11:32 UTC, merged

2024-08-02 11:37 UTC, wcawijngaards commented
Thank you for the review! Added the changes and squashed and merged it into the repo.