Stream reuse
NLnetLabs/unbound pull request #283
Opened 2020-08-04 09:49 UTC by wcawijngaards

This implements stream reuse towards Unbound's upstream servers.  When a query is sent to a server for which there is an open socket, the socket is reused without opening a new stream to the server.  For TCP and TLS queries, for IPv4 and IPv6.  Sockets are opened per-thread, since the per-thread worker keeps track of the reused sockets.

2020-08-04 09:52 UTC, wcawijngaards commented
This PR fixes issue #47

2020-10-02 14:10 UTC, pyropeter commented
Will this be part of 1.12.0 or are you in feature freeze?

2020-10-02 14:24 UTC, wcawijngaards commented
This is not in 1.12.0, because we are in feature freeze for it.  It is waiting for review, and maybe some fixes after that.

2020-10-10 21:41 UTC, djcater commented
Will this cover both upstream DNS-Over-TLS connections and upstream DNS-Over-HTTPS connections?

2020-10-12 13:17 UTC, ralphdolmans commented
> Will this cover both upstream DNS-Over-TLS connections and upstream DNS-Over-HTTPS connections?

There is no upstream DoH support in Unbound yet, only downstream. If upstream DoH will be added at a later stage it will benefit from the changes in the PR.

2020-10-16 11:12 UTC, ralphdolmans approved these changes
Looks good to me!

2020-11-02 22:09 UTC, iz8mbw commented
Ready to merge? 😁

2020-11-10 10:55 UTC, wcawijngaards commented
The branch is ready for use, it is waiting for review(s), before merge.

2020-11-23 07:57 UTC, gthess requested changes
Looks good to me also!

I have a question and some nits.
What is the benefit of `MAX_REUSE_TCP_QUERIES`?

The nits:
1. Shouldn't `log_reuse_tcp(<number>, ...)` turn to `log_reuse_tcp(<level>, ...)` and
  `verbose(<number>, ...)` turn to `verbose(<level>, ...)`? Unless they are for dev debugging and will be removed?
2. The `ssl_reuse.tdir` and the `ssl_reuse.*` files therein could be renamed to tls_reuse.

2020-11-23 07:57 UTC, gthess commented on services/outside_network.c
> +		if(verbosity >= 5 && pend->query->pkt_len > 12+2+2 &&
Verbosity number check

2020-11-23 07:57 UTC, gthess commented on services/outside_network.c
> +		if(verbosity >= 5 && w->pkt_len > 12+2+2 &&
Verbosity number check

2020-11-23 07:57 UTC, gthess commented on services/outside_network.c
> +			return 0;
The two `if(pend->c->tcp_write_and_read)` can be combined

2020-11-23 07:57 UTC, gthess commented on services/outside_network.c
> +	return curid + 1 + (select - count);
Just a note: this last resort seems less random to me but since we only need the ID for differentiating the queries in the same TCP connection I don't see a problem.

2020-11-23 07:57 UTC, gthess commented on services/outside_network.h
> +	 * and then ptr value for several times same address in tree */
The comment about the key is not very clear.

2020-11-23 07:57 UTC, gthess commented on testdata/ssl_reuse.tdir/ssl_reuse.conf
> +	ssl-upstream: yes
Could use the `tls-upstream` option instead.

2020-11-23 07:57 UTC, gthess commented on testdata/ssl_reuse.tdir/ssl_reuse.test
> +sleep 15
Mismatch between print value and command.

2020-11-23 07:57 UTC, gthess commented on testdata/tcp_reuse.tdir/tcp_reuse.test
> +sleep 15
Mismatch between print value and command.

2020-11-23 08:05 UTC, wcawijngaards commented
The `MAX_REUSE_TCP_QUERIES` is so that it does not make too many queries at the same time to a destination.  This is because it starts to queue up, but then in terms of TCP buffers, and also, if the connection fails for some reason that is a lot of queries.  So I thought it best not to have too many at the same time on one stream, at the level of thousands it should remove overhead costs just fine.

2020-11-23 08:25 UTC, iz8mbw commented
Hi. A my personal note, if I have correctly understood, the connection timeout of reuse is hard-coded to 30 seconds.
This means that the ESTHABILISHED TCP connection to upstream remains ESTHABILISHED up to 30 seconds (if no new DNS query are made within these 30 seconds).
I think 30 seconds is a low value because if no DNS queries are made for 30 seconds the reuse is useless because unbound will go to create a new connection to upstream.
Can be this value increased? I think 60 seconds make more sense.
Thank you.

2020-11-23 08:37 UTC, wcawijngaards commented on services/outside_network.c
> +		if(verbosity >= 5 && pend->query->pkt_len > 12+2+2 &&
fixed.

2020-11-23 08:38 UTC, wcawijngaards commented on services/outside_network.c
> +		if(verbosity >= 5 && w->pkt_len > 12+2+2 &&
fixed.

2020-11-23 08:40 UTC, wcawijngaards commented on services/outside_network.c
> +			return 0;
okay.

2020-11-23 08:41 UTC, wcawijngaards commented on services/outside_network.c
> +	return curid + 1 + (select - count);
It is the same randomness? I thought?  Because it picks a random item from the list of available items?

2020-11-23 08:45 UTC, wcawijngaards commented on services/outside_network.h
> +	 * and then ptr value for several times same address in tree */
Updated it.

2020-11-23 08:45 UTC, wcawijngaards commented on testdata/ssl_reuse.tdir/ssl_reuse.conf
> +	ssl-upstream: yes
fixed.

2020-11-23 08:45 UTC, wcawijngaards commented on testdata/ssl_reuse.tdir/ssl_reuse.test
> +sleep 15
fixed.

2020-11-23 08:46 UTC, wcawijngaards commented on testdata/tcp_reuse.tdir/tcp_reuse.test
> +sleep 15
fixed.

2020-11-23 09:37 UTC, wcawijngaards commented
Sure, increased the reuse time to 60 seconds in https://github.com/NLnetLabs/unbound/pull/283/commits/6b97cb1dd127125f99ac44df62bfcfc07b5fe1c3 .

2020-11-23 15:17 UTC, gthess commented on services/outside_network.c
> +	return curid + 1 + (select - count);
Upon closer reading this looks good!

2020-11-23 15:19 UTC, gthess approved these changes
Thanks for incorporating the feedback, looks good to me!

2020-11-24 07:21 UTC, merged

2020-12-02 13:57 UTC, pengelana commented
Unbound 1.12.0 with patch from #283 and `--enable-tfo-client` & `--enable-tfo-server` will produce error:

`error: read (in tcp s): Transport endpoint is not connected for xxx.xxx.xxx.xxx port 53`

~~~
dig @127.0.0.1 fedoraproject.org

;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 40656
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;fedoraproject.org.             IN      A

;; Query time: 213 msec
~~~

2020-12-02 14:43 UTC, wcawijngaards commented
The fix is in commit https://github.com/NLnetLabs/unbound/commit/0502ab3026af59673b21133eb7c5a72126b37d66 . Thanks for the report!