Adds SVCB parameter key 7 (dohpath)
NLnetLabs/unbound pull request #547
Opened 2021-10-04 18:55 UTC by okanaganrusty

PR to add support for `dohpath` in the SVCB request.

Supporting issue #501

https://datatracker.ietf.org/doc/html/draft-schwartz-svcb-dns-00#section-5.1

2021-10-05 11:34 UTC, wcawijngaards commented
Thank you for the code! This looks like it implements the dohpath option for SVCB and HTTPS fine. The document is still a draft, and because we do not want to create a too-early deployment issue, we do not want to ship this at this early stage. It would be best if we waited for discussion at the IETF to complete.

Meanwhile, for experimentation there can be code. The code from the diff of this pullrequest can perhaps help people that want it. Deploy by applying the patch at https://github.com/NLnetLabs/unbound/pull/547.diff and then dohpath should work. Another way, but perhaps later, is to add compile time switches that default to off, that turn on this new feature.

2021-10-19 14:53 UTC, TCY16 requested changes
Hi @okanaganrusty,

Thanks again for the code. I found two small changes, but overall it looks very nice :)

2021-10-19 14:53 UTC, TCY16 commented on sldns/str2wire.c
> +
This write could result in a buffer overflow, as the `rd_len` isn't checked before writing the data. It's missing:
```suggestion
	if (*rd_len < 4 + dst_len)
		return LDNS_WIREPARSE_ERR_BUFFER_TOO_SMALL;
```

2021-10-19 14:53 UTC, TCY16 commented on testdata/svcb.tdir/svcb.success-cases.zone.cmp
> +s10.success-cases.	3600	IN	HTTPS	0 . alpn="h2" ipv4hint="127.0.0.1" ipv6hint="fe80::1" dohpath="/dns-query?{dns}"
This test seems to fail currently. Removing the quotes around the ipv*hints fixes this.
```suggestion
s10.success-cases.	3600	IN	HTTPS	0 . alpn="h2" ipv4hint=127.0.0.1 ipv6hint=fe80::1 dohpath="/dns-query?{dns}"
```

2022-12-06 09:54 UTC, jp-coding commented
Adressed by #739

2023-07-03 09:06 UTC, gthess commented
This seems to be addressed by #739 which is now merged; closing this.

2023-07-03 09:06 UTC, closed without merging