Better positioning of general EDNS option handling: revisited V2
NLnetLabs/unbound pull request #563
Opened 2021-11-02 12:05 UTC by TCY16

Rework from #549. Added an outgoing EDNS list for modules as well as a generic outgoing list, so these two don't collide during list-resets from modules.

2021-11-03 11:16 UTC, wtoorop requested changes
Make sure that all the tdir tests pass @TCY16 :-)

2021-11-03 11:16 UTC, wtoorop commented on daemon/worker.c
> +	edns->opt_list_modules_out = NULL;
```suggestion
```
EDNS options should not be reset!

2021-11-03 11:16 UTC, wtoorop commented on util/data/msgparse.h
> +	struct edns_option* opt_list_modules_out;
The inplace_cb_* functions are not only called from modules, so _modules_out is not a good name. 
```suggestion
	struct edns_option* opt_list_inplace_cb_out;
```

2021-11-03 11:16 UTC, wtoorop commented on util/data/msgparse.c
> +	return 0;
```suggestion
	return LDNS_RCODE_NOERROR;
```

2021-11-03 11:16 UTC, wtoorop commented on util/data/msgparse.c
> +		c->tcp_keepalive = 1;
Is this needed?
```suggestion
```

2021-11-03 11:16 UTC, wtoorop commented on daemon/worker.c
> +	if(!edns_bypass_cache_stage(edns.opt_list_in, &worker->env)) {
I wasn't sure, but @gthess confirms this is correct!

2021-11-03 11:16 UTC, wtoorop commented on util/data/msgparse.c
> +			break;
This parsing is done for both queries and responses. Accidentally `cfg` and `c` are only set for incoming queries, so option handling above is (incidentally) correct. But for responses (and for queries) we want callbacks to be able to have a look at the "incoming" options too, so we append them to `opt_list_in` always regardless of whether they are processed or not.
```suggestion
		default:
			break;
		}
		if(!edns_opt_list_append(&edns->opt_list_in,
				opt_code, opt_len, rdata_ptr, region)) {
			log_err("out of memory");
			return LDNS_RCODE_SERVFAIL;
```

2021-11-03 11:16 UTC, wtoorop commented on iterator/iterator.c
>  			qstate->region);
This could be a simple assignment if `parse_extract_edns()` above was called with `qstate->region`

2021-11-03 11:16 UTC, wtoorop commented on services/mesh.c
> +	int unique = unique_mesh_state(edns->opt_list_in, mesh->env);
@gthess says this is correct :)

2021-11-03 11:16 UTC, wtoorop commented on services/mesh.c
>  				s->s.region);
@gthess says it's fishy but okay

2021-11-03 11:16 UTC, wtoorop commented on services/mesh.c
> +	int unique = unique_mesh_state(edns->opt_list_in, mesh->env);
@gthess says fine! Same as before.

2021-11-03 11:16 UTC, wtoorop commented on services/mesh.c
> +			s->s.edns_opts_front_in = edns_opt_copy_region(edns->opt_list_in,
@gthess same same, so fishy but fine

2021-11-03 11:16 UTC, wtoorop commented on services/mesh.c
> +		) {
@gthess says ok!

2021-11-03 11:16 UTC, wtoorop commented on util/data/msgencode.c
> +		sldns_buffer_write_u16(pkt, opt->opt_code);
Padding could be here too
```suggestion
		if (opt->opt_code == LDNS_EDNS_PADDING) {
			padding_option = opt;
			continue;
		}
		sldns_buffer_write_u16(pkt, opt->opt_code);
```

2021-11-03 11:16 UTC, wtoorop commented on util/data/msgparse.c
>  		return 0;
```suggestion
		return LDNS_RCODE_NOERROR;
```

2021-11-03 11:16 UTC, wtoorop commented on util/data/msgparse.c
@TCY16 Could you please remove the return below too? And the `rcode` declaration? Thanks!
```suggestion
	/* ignore rrsigs */
	return parse_edns_options(rdata_ptr, rdata_len, edns, cfg, c, region);
```

2021-11-08 11:04 UTC, gthess commented on util/data/msgparse.c
>  	return 0;
This can go away now :)
```suggestion

```

2021-11-12 13:52 UTC, wcawijngaards approved these changes
This set of changes looks good to me. Two small removals of comments that are not needed. Good idea to report exact validation details in EDE though.

2021-11-12 13:52 UTC, wcawijngaards commented on validator/validator.c
> +
Excellent idea, but it does not belong here.
```suggestion
```

2021-11-12 13:52 UTC, wcawijngaards commented on validator/validator.c
> +		// @TODO ADD Error Code 6 - DNSSEC Bogus + text chain of trust?
Excellent idea, but also this comment does not belong here.
```suggestion
```

2021-11-15 14:02 UTC, wtoorop approved these changes

2021-11-15 14:14 UTC, merged