Update unbound.service.in
NLnetLabs/unbound pull request #575
Opened 2021-11-21 20:11 UTC by DavidOsipov

Main change is an intro of AmbientCapabilities, which allow to bind to privileged ports (1-1024) without super-user privileges, thus it's possible to further harden the process.

I'm testing other hardening options, probably will contribute soon.

2021-11-23 14:54 UTC, gthess requested changes
Hi, thanks for this. I have a few comments though.
@Maryse47 could you have a second look since you have contributed a lot in this file?

2021-11-23 14:54 UTC, gthess commented on contrib/unbound.service.in
> +SystemCallFilter=~@clock @cpu-emulation @debug @keyring @module @mount @obsolete @resources @privileged @debug @reboot
Isn't this redundant now since you only allow `@system-service` above?

2021-11-23 14:54 UTC, gthess commented on contrib/unbound.service.in
> +CapabilityBoundingSet=~CAP_SYS_ADMIN
Isn't this implied because `CAP_SYS_ADMIN` is not defined above?

2021-11-23 17:31 UTC, Maryse47 commented
The service still starts as root so this change may only decrease security in current state. `SystemCallFilter` and `CapabilityBoundingSet` changes should be explained somewhere.

2021-11-24 06:41 UTC, DavidOsipov commented on contrib/unbound.service.in
> +SystemCallFilter=~@clock @cpu-emulation @debug @keyring @module @mount @obsolete @resources @privileged @debug @reboot
Not really, here `@system-service` is a wide concept, which is allowed. And the line SystemCallFilter=~ restricts calls outside and inside `@system-service` concept. The bad thing is the [documentation ](https://www.freedesktop.org/software/systemd/man/systemd.exec.html) doesn't tell what is really inside the `@system-service`. 

If you have any info on redundancy, please share :)

2021-11-24 06:55 UTC, DavidOsipov commented
> The service still starts as root so I don't see actual hardening effect of this change. `SystemCallFilter` and `CapabilityBoundingSet` changes should be explained somewhere.

Ok, let me refine the changes and I'll open another pull request.

2021-11-24 06:55 UTC, closed without merging

2021-11-24 12:08 UTC, Maryse47 commented
Note that starting the service as non-root isn't an option either because it would break existing setups. I think those changes belong to downstream where you control specific execution environment.

2021-11-24 12:15 UTC, Maryse47 commented on contrib/unbound.service.in
> +SystemCallFilter=~@clock @cpu-emulation @debug @keyring @module @mount @obsolete @resources @privileged @debug @reboot
So undocumented feature being introduced without explanation :smile:

I think this describes the problem with this change.

2021-11-24 13:57 UTC, Maryse47 commented
There is alternative [portable](https://github.com/NLnetLabs/unbound/blob/master/contrib/unbound_portable.service.in) service which may be better target for running unprivileged.

2021-11-25 10:18 UTC, DavidOsipov commented
Ерфтл

> There is alternative [portable](https://github.com/NLnetLabs/unbound/blob/master/contrib/unbound_portable.service.in) service which may be better target for running unprivileged.

Thanks! I'll try to play around with it and yeap, running unbound as unprivileged service is a headache