0ttl
NLnetLabs/unbound pull request #866
Opened 2023-03-22 14:25 UTC by Philip-NLnetLabs

Fix for issue #860

2023-03-23 12:06 UTC, wcawijngaards approved these changes
I think it is a good idea to evict the message cache content when a 0 TTL new response is received. That synchronizes the content to the upstream content. The code looks good to have.

2023-03-23 12:06 UTC, wcawijngaards commented on services/cache/dns.c
> +		/* if the message is in then cache, remove that msg,
spelling fix.
```suggestion
		/* if the message is in the cache, remove that msg,
```

2023-03-23 12:06 UTC, wcawijngaards commented on testdata/serve_expired_0ttl_nodata.rpl
> +; - answer from upstream is NODATA; will be cached for NORR_TTL(5)
Fix TTL value in comment.
```suggestion
; - answer from upstream is NODATA; will be cached for the SOA negative TTL.
```

2023-03-23 12:06 UTC, wcawijngaards commented on testdata/serve_expired_0ttl_nxdomain.rpl
> +; - answer from upstream is NXDOMAIN; will be cached for NORR_TTL(5)
Fix TTL value in comment.
```suggestion
; - answer from upstream is NXDOMAIN; will be cached for the SOA negative TTL.
```

2023-04-25 18:05 UTC, gthess requested changes
Looks good!
But I believe we don't need the `msg_del_for_0ttl()` function anymore, just straight `msg_cache_remove()` in that place.
I would also like to see the same behavior for the ECS cache and cachedb.

2023-04-26 15:04 UTC, Philip-NLnetLabs commented
Yes, I'll change it to call msg_cache_remove. Maybe you can to the other two issues in a separate ticket.

2023-04-26 15:14 UTC, merged